# here we keep all configure servers file together
- name: "configure {{ component }} Server"
  hosts: all   # whatever we give after -i it will consider all
  connection: local 
  vars_files:
  - "variables-{{ env }}.yaml"  # we pass the required env, dont give environmnet its a reserved name
  become: yes
  roles:
  - "{{ component }}"

  # now we give component in cli 
  # component=bd/backed/frontend
  # ansible-playbook "filename" -e component=bd/backed/frontend


