- name: delete app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  #ignore_errors: yes

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

# - name: download and extract code
#   ansible.builtin.unarchive:
#     src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"  # we use componet here to replace frontend /backend
#     dest: "{{ app_location }}"
#     remote_src: yes

# we used s3 before now with version control and nexus we change it to
- name: download the artifact from nexus
  ansible.builtin.unarchive:
    src: "http://{{ nexus_url }}/repository/{{ component }}/com/expense/{{ component }}/{{ appVersion }}/{{ component }}-{{ appVersion }}.zip"
    dest: "{{ app_location }}"
    remote_src: yes